routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
/*
|--------------------------------------------------------------------------
| Plantilla
|--------------------------------------------------------------------------
| Ruta para la plantilla y todos sus elementos
|
*/

Route::get('/plantilla', function () {
    return view('plantilla/index');
});

Auth::routes();

Auth::routes(['verify' => true]);

Route::get('/password', function(){
    return redirect()->route('password.update');
});
Route::get('/resetcomplete', function(){
    Auth::logout();
    return view('auth/resetcomplete');
});

/*
|--------------------------------------------------------------------------
| Rutas con autenticación
|--------------------------------------------------------------------------
| Rutas para usuarios logueados
|
*/

Route::get('signup/activate/{user}/code/{code}', 'SignupActivateController@activarCuentaApi');

Route::middleware(['auth'])->group(function(){
	/*
	| Dashboard
	*/
	// Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/', 'dashboard\dashboardController@index');
	Route::get('/home', 'dashboard\dashboardController@index')->name('home');

	/*
	| Roles
	*/
	Route::resource('/roles', 'roles\rolesController');
	Route::get('/roles/{role}/servicios', 'roles\serviciosController@index');
	Route::post('/roles/{role}/servicios', 'roles\serviciosController@store');

	/*
	| Menu
	*/
	Route::resource('/menu', 'menu\menuController');

	/*
	| Servicios
	*/
	Route::resource('/servicios', 'servicios\serviciosController');
	Route::post('/servicios/{id}', 'servicios\serviciosController@servicioDetalles');
	Route::get('/nuevos_servicios', 'servicios_al_cliente\servicios_al_clienteController@index')->name('servicios_al_cliente.index');
	Route::post('/nuevos_servicios/buscar', 'servicios_al_cliente\servicios_al_clienteController@buscar')->name('servicios_al_cliente.buscar');
	Route::post('/nuevos_servicios/mostrar', 'servicios_al_cliente\servicios_al_clienteController@mostrar')->name('servicios_al_cliente.mostrar');
	Route::post('/nuevos_servicios/cformula', 'servicios_al_cliente\servicios_al_clienteController@cformula')->name('servicios_al_cliente.cformula');
	Route::post('/nuevos_servicios/pformula', 'servicios_al_cliente\servicios_al_clienteController@pformula')->name('servicios_al_cliente.pformula');
	Route::post('/nuevos_servicios/hacer', 'servicios_al_cliente\servicios_al_clienteController@hacer')->name('servicios_al_cliente.hacer');
	Route::post('/nuevos_servicios/cuse', 'servicios_al_cliente\servicios_al_clienteController@cuse')->name('servicios_al_cliente.cuse');
	Route::post('/nuevos_servicios/puse', 'servicios_al_cliente\servicios_al_clienteController@puse')->name('servicios_al_cliente.puse');
	Route::post('/nuevos_servicios/recibir', 'servicios_al_cliente\servicios_al_clienteController@recibir')->name('servicios_al_cliente.recibir');

	// Route::get('/Hacer_nohacer', 'hacer_no_hacer\hacerNoHacerController@index')->name('hacer_no_hacer.index');
	// Route::post('/Hacer_nohacer', 'hacer_no_hacer\hacerNoHacerController@store')->name('hacer_no_hacer.store');
	// Route::get('/Hacer_nohacer/{id}', 'hacer_no_hacer\hacerNoHacerController@edit')->name('hacer_no_hacer.edit');
	// Route::post('/Hacer_nohacer/{id}', 'hacer_no_hacer\hacerNoHacerController@update')->name('hacer_no_hacer.update');
	// Route::get('/Hacer_nohacer/destroy/{id}', 'hacer_no_hacer\hacerNoHacerController@destroy')->name('hacer_no_hacer.destroy');

	Route::get('/do/{ye}', 'hacer_no_hacer\hacerNoHacerController@index')->name('hacer_no_hacer.index');
	Route::post('/do', 'hacer_no_hacer\hacerNoHacerController@store')->name('hacer_no_hacer.store');
	Route::get('/do /{id?}', 'hacer_no_hacer\hacerNoHacerController@edit')->name('hacer_no_hacer.edit');
	Route::post('/do /{id}', 'hacer_no_hacer\hacerNoHacerController@update')->name('hacer_no_hacer.update');
	Route::get('/do/destroy/{id}', 'hacer_no_hacer\hacerNoHacerController@destroy')->name('hacer_no_hacer.destroy');

	Route::get('/dont/{ye}', 'hacer_no_hacer\hacerNoHacerController@index')->name('nohacer_no_hacer.index');
	Route::post('/dont', 'hacer_no_hacer\hacerNoHacerController@store')->name('nohacer_no_hacer.store');
	Route::get('/dont/{id}', 'hacer_no_hacer\hacerNoHacerController@edit')->name('nohacer_no_hacer.edit');
	Route::post('/dont/{id}', 'hacer_no_hacer\hacerNoHacerController@update')->name('nohacer_no_hacer.update');
	Route::get('/dont/destroy/{id}', 'hacer_no_hacer\hacerNoHacerController@destroy')->name('nohacer_no_hacer.destroy');
	
	
	

	

	
	/*
	| Producto
	*/
	// Route::resource('/producto/marca', 'producto\marcaController');
	Route::resource('/marca', 'producto\marcaController');
	Route::get('/producto/marca/categoria/{id?}', 'producto\marcaController@marcaCategoria')->name('marca.categoria');
	// Route::resource('/producto/categoria', 'producto\categoriaController');
	Route::resource('/categoria', 'producto\categoriaController');
	Route::resource('/producto/producto', 'producto\productoController');
	Route::get('/importar/producto/', 'producto\importarController@index')->name('producto.importar');
	Route::post('/importar/producto/importar', 'producto\importarController@subirArchivo')->name('producto.subir.archivo');
	Route::get('/producto/exportar/formato', 'producto\exportarController@exportarFormatoModeloProducto')->name('producto.exportar.formato');
	Route::get('/producto/exportar/productos', 'producto\exportarController@exportarProductos')->name('producto.exportar.productos');

	/*
	| Mis categorias
	*/
	Route::get('/categorias/buscarProfesional', 'usuarios\CategoriasController@buscarProfesional')->name('categorias.buscarProfesional');
	Route::get('/categorias/usuario/{id?}', 'usuarios\CategoriasController@categoriasUsuario')->name('categorias.usuario');
	Route::post('/categorias/usuario/guardar', 'usuarios\CategoriasController@categoriasUsuarioGuardar')->name('categorias.usuario.guardar');
	Route::get('/categorias/listarCategorias', 'usuarios\CategoriasController@listarCategorias')->name('categorias.listarCategorias');
	Route::get('/miscategorias/usuario/{id}', 'usuarios\MisCategoriasController@index');
	Route::post('/miscategorias/usuario/{id}', 'usuarios\MisCategoriasController@modificarCategorias');
	Route::resource('/categorias', 'usuarios\CategoriasController');
	Route::post('/categorias/buscar', 'usuarios\CategoriasController@buscarCategorias')->name('categorias.buscar');

	/*
	| Administrar usuarios
	*/
	Route::resource('/usuarios', 'usuarios\UsuariosController');




});

app/Producto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Producto extends Model
{
    protected $table = 'producto';

    protected $fillable = [
        'nombre', 'categoria_id', 'medida', 'numero', 'descripcion', 'user_id', 'tipo'
    ];

    public function categoria(){
        return $this->hasOne('App\Categoria', 'id', 'categoria_id');
    }

    public function propietario(){
        return $this->hasOne('App\User', 'id', 'user_id');
    }

    public function getNombreAttribute($value)
    {
        return strtoupper($value);
    }
}

app/Http/Controllers/API/ProductosController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Marca;
use App\Categoria;
use App\Producto;

class ProductosController extends Controller
{
    public function buscarMarca(Request $r){
        $marca = Marca::where('nombre', 'like', '%' . $r->string . '%')->get();
        return response()->json($marca);
    }

    public function buscarMarcaCategoria(Request $r, $marca_id){
        $categoria = Categoria::where('nombre', 'like', '%' . $r->string . '%')
                            ->where('marca_id', $marca_id)
                            ->get()
                            ->unique('nombre')->flatten();
        return response()->json($categoria);
    }

    public function buscarMarcaCategoriaProducto(Request $r, $categoria_id){
        $producto = Producto::where('nombre', 'like', '%' . $r->string . '%')
                            ->where('categoria_id', $categoria_id)
                            // ->where('categoria_id', $categoria_id)
                            ->get()->unique('nombre')->flatten();

        return response()->json($producto);
    }

    public function buscarMarcaCategoriaProductoNumero(Request $r, $categoria_id){
        $producto = Producto::where('nombre', 'like', '%' . $r->nombreProducto . '%')
                            ->where('numero', 'like', '%'. $r->numero .'%')
                            ->where('categoria_id', $categoria_id)
                            ->get();
        return response()->json($producto);
    }
}

app/Http/Controllers/producto/categoriaController.php
<?php

namespace App\Http\Controllers\producto;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Controllers\producto\marcaController as Marca;
use Validator;
use App\Categoria;
use Auth;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;

class categoriaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categorias = $this->categoria()->paginate(10);
        return view('categoria.index', compact('categorias'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $marca = new Marca;
        $marcas = $marca->marca()->get();
        return view('categoria.create', compact('marcas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make(
            $request->all(), [
                'nombre' => 'required|min:3',
            ],
            [
                'nombre.required' => 'Indique el nombre de la categoria',
                'nombre.min' => 'Mínimo tres caracteres para el nombre',
            ]
        );

        if ($validator->fails()) {
            return redirect('producto/categoria/create')
                        ->withErrors($validator)
                        ->with('error', 'Error en la validación del formulario')
                        ->withInput();
        }

        $categoria = new Categoria;
        $categoria->user_id= $this->usuario()->id;
        $categoria->nombre = $request->nombre;
        $categoria->marca_id = $request->marca;
        if($request->file('url_foto')){
            $imagen = $request->file('url_foto');          
    
                $nombreImagen = Str::uuid() . "." . $request->url_foto->extension();
                $imagen->originalName = $nombreImagen;
    
                if (!Storage::disk('public')->exists('categorias')) {
                  Storage::disk('public')->makeDirectory('categorias');
                }
    
                Storage::disk('public')->put('categorias/' . $nombreImagen, file_get_contents($imagen));
    
                $categoria->url_foto = url('storage/categorias') . '/' . $nombreImagen;
        }
        $categoria->save();

        return redirect()->route('categoria.create')->with('creado', 'Nueva categoria creada');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categoria = $this->categoria($id)->first();
        $marca = new Marca;
        $marcas = $marca->marca()->get();
        return view('categoria.edit', compact('categoria', 'marcas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make(
            $request->all(), [
                'nombre' => 'required|min:3',
            ],
            [
                'nombre.required' => 'Indique el nombre de la categoria',
                'nombre.min' => 'Mínimo tres caracteres para el nombre',
            ]
        );

        if ($validator->fails()) {
            return redirect('producto/categoria/'. $id .'/edit')
                        ->withErrors($validator)
                        ->with('error', 'Error en la validación del formulario')
                        ->withInput();
        }

        $categoria = $this->categoria($id)->first();
        $categoria->nombre = $request->nombre;
        $categoria->marca_id = $request->marca;
        if($request->file('url_foto')){
            $imagen = $request->file('url_foto');          
    
                $nombreImagen = Str::uuid() . "." . $request->url_foto->extension();
                $imagen->originalName = $nombreImagen;
    
                if (!Storage::disk('public')->exists('categorias')) {
                  Storage::disk('public')->makeDirectory('categorias');
                }
    
                Storage::disk('public')->put('categorias/' . $nombreImagen, file_get_contents($imagen));
    
                $categoria->url_foto = url('storage/categorias') . '/' . $nombreImagen;
        }
        $categoria->save();

        return redirect()->route('categoria.edit', ['id' => $id])->with('actualizado', 'La categoria se ha actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function categoria($id=''){
        if($id == ''){
            $categoria = Categoria::orderBy('id', 'desc');
        }else
        {
            $categoria = Categoria::where('id', $id);
        }

        return $categoria;

    }
    public function usuario(){

        return Auth::user();
    }
}

app/Http/Controllers/producto/exportarController.php
<?php

namespace App\Http\Controllers\producto;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Maatwebsite\Excel\Facades\Excel;
use App\Exports\ExportarFormatoModeloProducto;
use App\Exports\ExportarProductos;

class exportarController extends Controller
{
    public function exportarFormatoModeloProducto()
    {
        return Excel::download(new ExportarFormatoModeloProducto, 'formato_importar_productos.xlsx');
    }

    public function exportarProductos()
    {
        return Excel::download(new ExportarProductos, 'todos_productos.xlsx');
    }
}

app/Http/Controllers/producto/importarController.php
<?php

namespace App\Http\Controllers\producto;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Imports\importarProducto;
use Maatwebsite\Excel\Facades\Excel;

class importarController extends Controller
{
    public function index(){
        return view('importar.index');
    }

    public function subirArchivo(Request $request){

        if(!$request->hasFile('archivo')){
            return response()->json("Archivo no seleccionado");
        }

        try{
            Excel::import(new importarProducto, $request->archivo);
        }catch(\Exception $e){
           
            return response()->json(['error'=>$e]);
        }
        
        return response()->json('completado');
    }
}

resources/views/producto/create.blade.php
@extends('layout.index')

@section('libreriascss')
{{-- Formularios --}}
<!--Morris css-->
<link rel="stylesheet" href="{{url('assets/plugins/morris/morris.css')}}">
{{-- Notificaciones emergentes --}}
<!--Toastr css-->
<link rel="stylesheet" href="{{url('assets/plugins/toastr/build/toastr.css')}}">
<link rel="stylesheet" href="{{url('assets/plugins/toaster/garessi-notif.css')}}">
@endsection

@section('cuerpo')
{{-- Formularios - General Elements --}}
<div class="row">
	<div class="col-lg-12">
		<div class="card">
			<div class="card-header">
				<h4>Nuevo producto</h4>
            </div>
			<div class="card-body">
				<form enctype="multipart/form-data" name="frmProductos" class="form-horizontal" method="POST" action="{{route('producto.store')}}">
					@csrf
					<div class="form-group row">
						<label class="col-md-3 col-form-label">Nombre</label>
						<div class="col-md-9">
							<input type="text" name="nombre" id="nombre" class="form-control" value="{{old('nombre')}}" placeholder="">
						</div>
                    </div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label">Medida</label>
						<div class="col-md-9">
							<select class="form-control" id="medida" name="medida" data-url="{{old('medida')}}">
                                <option value="gr">gr</option>
								<option value="oz">oz</option>
							</select>
						</div>
						
                    </div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label">Numero</label>
						<div class="col-md-9">
							<input type="text" name="numero" id="numero" class="form-control" value="{{old('numero')}}" placeholder="">
						</div>
                    </div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label">Descripción</label>
						<div class="col-md-9">
							<input type="text" name="descripcion" id="descripcion" class="form-control" value="{{old('descripcion')}}" placeholder="">
						</div>
                    </div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label">Tipo uso</label>
						<div class="col-md-9">
							<select class="form-control" id="Tipo_uso" name="Tipo_uso">
                        	        <option value="Local">Local</option>
									<option value="Cliente">Cliente</option>            
							</select>
						</div>
                    </div>
                    <div class="form-group row">
						<label class="col-md-3 col-form-label">Marca</label>
						<div class="col-md-9">
							<select class="form-control" id="marca" name="marca" data-url="{{route('marca.categoria')}}">
							@if(count($marcas) != 0)
                                @foreach($marcas as $marca)
                                <option value='{{$marca->id}}'>{{$marca->nombre}}</option>
                                @endforeach
							@endif
							</select>
						</div>
					</div>
                    <div class="form-group row">
						<label class="col-md-3 col-form-label">Categoria</label>
						<div class="col-md-9">
							<select class="form-control" id="categorias" name="categorias">
							@if(count($categorias) != 0)
                                @foreach($categorias as $categoria)
                                <option value='{{$categoria->id}}'>{{$categoria->nombre}}</option>
                                @endforeach
							@endif
							</select>
						</div>
					</div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label">Imagen</label>
						<div class="col-md-9">
							<input id="url_foto" name="url_foto" type="file" accept="image/*" class="form-control">
						</div>
					</div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label"></label>
						<div class="col-md-9">
							<button type="submit" class="btn btn-info">Guardar</button>
							<a href="{{route('producto.index')}}" class="btn btn-primary">Volver</a>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

@if(session('creado'))
	<div style="display: none;" id="actualizado" name="actualizado" class="alert alert-success" data-mensaje="{{session('creado')}}"></div>
@endif
@if($errors->has('nombre'))
	<div style="display: none;" id="error" name="error" class="alert alert-success" data-mensaje="{{$errors->first('nombre')}}"></div>
@endif
@if($errors->has('medida'))
	<div style="display: none;" id="error" name="error" class="alert alert-success" data-mensaje="{{$errors->first('medida')}}"></div>
@endif
@if($errors->has('numero'))
	<div style="display: none;" id="error" name="error" class="alert alert-success" data-mensaje="{{$errors->first('numero')}}"></div>
@endif
@if($errors->has('categorias'))
	<div style="display: none;" id="error" name="error" class="alert alert-success" data-mensaje="{{$errors->first('categorias')}}"></div>
@endif


@endsection

@section('libreriasjavascript')
{{-- Notificaciones emergentes --}}
<!--Toastr js-->
<script src="{{url('assets/plugins/toastr/build/toastr.min.js')}}"></script>
<script src="{{url('assets/plugins/toaster/garessi-notif.js')}}"></script>
@endsection

@section('javascript')
<script type="text/javascript">
$(document).ready(function($) {
	if($('#actualizado').length){
		$mensaje = $('#actualizado').data('mensaje');
		toastr.success($mensaje, 'inBe');
	}
	if($('#error').length){
		$mensaje = $('#error').data('mensaje');
		toastr.error($mensaje, 'inBe');
	}

    $('#marca').change(function(){
        var $id=$(this).val();
        var $url=$(this).data('url') + '/' + $id;
        $('#categorias').empty();
        $.get($url, function(data){
            for($i=0; $i<data[0].length; $i++){
                console.log(data[0][$i]['nombre']);
                $('#categorias').append($('<option>', {value:data[0][$i]['id'], text:data[0][$i]['nombre']}));
            }
        });
    })
});
</script>
@endsection

resources/views/producto/edit.blade.php
@extends('layout.index')

@if (!session()->has('back_previous_button'))
  {{session()->put('back_previous_button', url()->previous())}}
@endif

@section('libreriascss')
{{-- Formularios --}}
<!--Morris css-->
<link rel="stylesheet" href="{{url('assets/plugins/morris/morris.css')}}">
{{-- Notificaciones emergentes --}}
<!--Toastr css-->
<link rel="stylesheet" href="{{url('assets/plugins/toastr/build/toastr.css')}}">
<link rel="stylesheet" href="{{url('assets/plugins/toaster/garessi-notif.css')}}">
@endsection

@section('cuerpo')
{{-- Formularios - General Elements --}}
<div class="row">
	<div class="col-lg-12">
		<div class="card">
			<div class="card-header">
				<h4>Nuevo menú</h4>
            </div>
			<div class="card-body">
				<form enctype="multipart/form-data" name="frmProductos" class="form-horizontal" method="POST" action="{{action('producto\productoController@update', ['id' => $producto->id])}}">
					@csrf
					@method('PUT')
					<div class="form-group row">
						<label class="col-md-3 col-form-label">Nombre</label>
						<div class="col-md-9">
							<input type="text" name="nombre" id="nombre" class="form-control" value="{{old('nombre') ? old('nombre') : $producto->nombre}}">
						</div>
                    </div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label">Medida</label>
						<div class="col-md-9">
							<select class="form-control" id="medida" name="medida" data-url="{{old('medida')}}">
                                <option value="gr" {{ $producto->medida == 'gr' ? 'selected' : ''}}>gr</option>
								<option value="oz" {{ $producto->medida == 'oz' ? 'selected' : ''}}>oz</option>
							</select>
						</div>
                    </div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label">Numero</label>
						<div class="col-md-9">
							<input type="text" name="numero" id="numero" class="form-control" value="{{old('numero') ? old('numero') : $producto->numero}}">
						</div>
                    </div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label">Descripción</label>
						<div class="col-md-9">
							<input type="text" name="descripcion" id="descripcion" class="form-control" value="{{old('descripcion') ? old('descripcion') : $producto->descripcion}}">
						</div>
                    </div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label">Tipo uso</label>
						<div class="col-md-9">
							<select class="form-control"  id="Tipo_uso" name="Tipo_uso">
                        	        <option value="Local" {{ $producto->tipo == 'Local' ? 'selected' : ''}} >Local</option>
									<option value="Cliente" {{ $producto->tipo == 'Cliente' ? 'selected' : ''}}>Cliente</option>            
							</select>
						</div>
                    </div>
                    <div class="form-group row">
						<label class="col-md-3 col-form-label">Marca</label>
						<div class="col-md-9">
							<select class="form-control" id="marca" name="marca" data-url="{{route('marca.categoria')}}">
                                @foreach($marcas as $marca)
                                <option value='{{$marca->id}}' {{$marca->id == $producto->categoria->marca_id ? 'selected' : ''}}>{{$marca->nombre}}</option>
                                @endforeach
							</select>
						</div>
					</div>
                    <div class="form-group row">
						<label class="col-md-3 col-form-label">Categoria</label>
						<div class="col-md-9">
							<select class="form-control" id="categorias" name="categorias">
                                @foreach($categorias as $categoria)
                                <option value='{{$categoria->id}}' {{$categoria->id == $producto->categoria_id ? 'selected' : ''}}>{{$categoria->nombre}}</option>
                                @endforeach
							</select>
						</div>
					</div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label"></label>
						<div class="col-md-9">
							<img src="{{$producto->url_foto}}" alt="Smiley face" height="80" width="80">
						</div>
					</div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label">Imagen</label>
						<div class="col-md-9">
							<input id="url_foto" name="url_foto" type="file" accept="image/*" class="form-control">
						</div>
					</div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label"></label>
						<div class="col-md-9">
							<button type="submit" class="btn btn-info">Guardar</button>
							{{--  <a href="{{route('producto.index')}}" class="btn btn-primary">Volver</a>  --}}
							<a href="{{ session()->get('back_previous_button')}}" class="btn btn-primary">Volver</a>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

@if(session('actualizado'))
	<div style="display: none;" id="actualizado" name="actualizado" class="alert alert-success" data-mensaje="{{session('actualizado')}}"></div>
@endif
@if($errors->has('nombre'))
	<div style="display: none;" id="error" name="error" class="alert alert-success" data-mensaje="{{$errors->first('nombre')}}"></div>
@endif
@if($errors->has('medida'))
	<div style="display: none;" id="error" name="error" class="alert alert-success" data-mensaje="{{$errors->first('medida')}}"></div>
@endif
@if($errors->has('numero'))
	<div style="display: none;" id="error" name="error" class="alert alert-success" data-mensaje="{{$errors->first('numero')}}"></div>
@endif

@endsection

@section('libreriasjavascript')
{{-- Notificaciones emergentes --}}
<!--Toastr js-->
<script src="{{url('assets/plugins/toastr/build/toastr.min.js')}}"></script>
<script src="{{url('assets/plugins/toaster/garessi-notif.js')}}"></script>
@endsection

@section('javascript')
<script type="text/javascript">
$(document).ready(function($) {
	if($('#actualizado').length){
		$mensaje = $('#actualizado').data('mensaje');
		toastr.success($mensaje, 'inBe');
	}
	if($('#error').length){
		$mensaje = $('#error').data('mensaje');
		toastr.error($mensaje, 'inBe');
	}

    $('#marca').change(function(){
        var $id=$(this).val();
        var $url=$(this).data('url') + '/' + $id;
        $('#categorias').empty();
        $.get($url, function(data){
            for($i=0; $i<data[0].length; $i++){
                console.log(data[0][$i]['nombre']);
                $('#categorias').append($('<option>', {value:data[0][$i]['id'], text:data[0][$i]['nombre']}));
            }
        });
    })
});
</script>
@endsection