routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
/*
|--------------------------------------------------------------------------
| Plantilla
|--------------------------------------------------------------------------
| Ruta para la plantilla y todos sus elementos
|
*/

Route::get('/plantilla', function () {
    return view('plantilla/index');
});

Auth::routes();

Auth::routes(['verify' => true]);

Route::get('/password', function(){
    return redirect()->route('password.update');
});
Route::get('/resetcomplete', function(){
    Auth::logout();
    return view('auth/resetcomplete');
});

/*
|--------------------------------------------------------------------------
| Rutas con autenticación
|--------------------------------------------------------------------------
| Rutas para usuarios logueados
|
*/

Route::get('signup/activate/{user}/code/{code}', 'SignupActivateController@activarCuentaApi');

Route::middleware(['auth'])->group(function(){
	/*
	| Dashboard
	*/
	// Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/', 'dashboard\dashboardController@index');
	Route::get('/home', 'dashboard\dashboardController@index')->name('home');

	/*
	| Roles
	*/
	Route::resource('/roles', 'roles\rolesController');
	Route::get('/roles/{role}/servicios', 'roles\serviciosController@index');
	Route::post('/roles/{role}/servicios', 'roles\serviciosController@store');

	/*
	| Menu
	*/
	Route::resource('/menu', 'menu\menuController');

	/*
	| Servicios
	*/
	Route::resource('/servicios', 'servicios\serviciosController');
	Route::post('/servicios/{id}', 'servicios\serviciosController@servicioDetalles');
	Route::get('/nuevos_servicios', 'servicios_al_cliente\servicios_al_clienteController@index')->name('servicios_al_cliente.index');
	Route::post('/nuevos_servicios/buscar', 'servicios_al_cliente\servicios_al_clienteController@buscar')->name('servicios_al_cliente.buscar');
	Route::post('/nuevos_servicios/mostrar', 'servicios_al_cliente\servicios_al_clienteController@mostrar')->name('servicios_al_cliente.mostrar');
	Route::post('/nuevos_servicios/cformula', 'servicios_al_cliente\servicios_al_clienteController@cformula')->name('servicios_al_cliente.cformula');
	Route::post('/nuevos_servicios/pformula', 'servicios_al_cliente\servicios_al_clienteController@pformula')->name('servicios_al_cliente.pformula');
	Route::post('/nuevos_servicios/hacer', 'servicios_al_cliente\servicios_al_clienteController@hacer')->name('servicios_al_cliente.hacer');
	Route::post('/nuevos_servicios/cuse', 'servicios_al_cliente\servicios_al_clienteController@cuse')->name('servicios_al_cliente.cuse');
	Route::post('/nuevos_servicios/puse', 'servicios_al_cliente\servicios_al_clienteController@puse')->name('servicios_al_cliente.puse');
	Route::post('/nuevos_servicios/recibir', 'servicios_al_cliente\servicios_al_clienteController@recibir')->name('servicios_al_cliente.recibir');

	// Route::get('/Hacer_nohacer', 'hacer_no_hacer\hacerNoHacerController@index')->name('hacer_no_hacer.index');
	// Route::post('/Hacer_nohacer', 'hacer_no_hacer\hacerNoHacerController@store')->name('hacer_no_hacer.store');
	// Route::get('/Hacer_nohacer/{id}', 'hacer_no_hacer\hacerNoHacerController@edit')->name('hacer_no_hacer.edit');
	// Route::post('/Hacer_nohacer/{id}', 'hacer_no_hacer\hacerNoHacerController@update')->name('hacer_no_hacer.update');
	// Route::get('/Hacer_nohacer/destroy/{id}', 'hacer_no_hacer\hacerNoHacerController@destroy')->name('hacer_no_hacer.destroy');

	Route::get('/do/{ye}', 'hacer_no_hacer\hacerNoHacerController@index')->name('hacer_no_hacer.index');
	Route::post('/do', 'hacer_no_hacer\hacerNoHacerController@store')->name('hacer_no_hacer.store');
	Route::get('/do /{id?}', 'hacer_no_hacer\hacerNoHacerController@edit')->name('hacer_no_hacer.edit');
	Route::post('/do /{id}', 'hacer_no_hacer\hacerNoHacerController@update')->name('hacer_no_hacer.update');
	Route::get('/do/destroy/{id}', 'hacer_no_hacer\hacerNoHacerController@destroy')->name('hacer_no_hacer.destroy');

	Route::get('/dont/{ye}', 'hacer_no_hacer\hacerNoHacerController@index')->name('nohacer_no_hacer.index');
	Route::post('/dont', 'hacer_no_hacer\hacerNoHacerController@store')->name('nohacer_no_hacer.store');
	Route::get('/dont/{id}', 'hacer_no_hacer\hacerNoHacerController@edit')->name('nohacer_no_hacer.edit');
	Route::post('/dont/{id}', 'hacer_no_hacer\hacerNoHacerController@update')->name('nohacer_no_hacer.update');
	Route::get('/dont/destroy/{id}', 'hacer_no_hacer\hacerNoHacerController@destroy')->name('nohacer_no_hacer.destroy');
	
	
	

	

	
	/*
	| Producto
	*/
	// Route::resource('/producto/marca', 'producto\marcaController');
	Route::resource('/marca', 'producto\marcaController');
	Route::get('/producto/marca/categoria/{id?}', 'producto\marcaController@marcaCategoria')->name('marca.categoria');
	// Route::resource('/producto/categoria', 'producto\categoriaController');
	Route::resource('/categoria', 'producto\categoriaController');
	Route::resource('/producto/producto', 'producto\productoController');
	Route::get('/importar/producto/', 'producto\importarController@index')->name('producto.importar');
	Route::post('/importar/producto/importar', 'producto\importarController@subirArchivo')->name('producto.subir.archivo');
	Route::get('/producto/exportar/formato', 'producto\exportarController@exportarFormatoModeloProducto')->name('producto.exportar.formato');
	Route::get('/producto/exportar/productos', 'producto\exportarController@exportarProductos')->name('producto.exportar.productos');

	/*
	| Mis categorias
	*/
	Route::get('/categorias/buscarProfesional', 'usuarios\CategoriasController@buscarProfesional')->name('categorias.buscarProfesional');
	Route::get('/categorias/usuario/{id?}', 'usuarios\CategoriasController@categoriasUsuario')->name('categorias.usuario');
	Route::post('/categorias/usuario/guardar', 'usuarios\CategoriasController@categoriasUsuarioGuardar')->name('categorias.usuario.guardar');
	Route::get('/categorias/listarCategorias', 'usuarios\CategoriasController@listarCategorias')->name('categorias.listarCategorias');
	Route::get('/miscategorias/usuario/{id}', 'usuarios\MisCategoriasController@index');
	Route::post('/miscategorias/usuario/{id}', 'usuarios\MisCategoriasController@modificarCategorias');
	Route::resource('/categorias', 'usuarios\CategoriasController');
	Route::post('/categorias/buscar', 'usuarios\CategoriasController@buscarCategorias')->name('categorias.buscar');

	/*
	| Administrar usuarios
	*/
	Route::resource('/usuarios', 'usuarios\UsuariosController');




});

app/Menus.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Menus extends Model
{
    protected $table = 'menus';

    protected $fillable = [
        'name', 'descripcion',
    ];
}

app/Http/Controllers/menu/menuController.php
<?php

namespace App\Http\Controllers\menu;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;
use App\Menus;

class menuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $menus = $this->menus()->paginate(10);
        return view('menu.index', compact('menus'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('menu.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make(
            $request->all(), [
                'name' => 'required|min:3',
            ],
            [
                'name.required' => 'Indique el nombre del menu',
                'name.min' => 'Mínimo tres caracteres para el nombre',
            ]
        );

        if ($validator->fails()) {
            return redirect('menu/create')
                        ->withErrors($validator)
                        ->with('error', 'Error en la validación del formulario')
                        ->withInput();
        }

        $menu = new Menus;
        $menu->name = $request->name;
        $menu->descripcion = $request->descripcion;
        $menu->save();

        return redirect('menu/create')->with('creado', 'Nuevo menú creado');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $menu = $this->menus($id)->first();
        return view('menu.edit', compact('menu'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make(
            $request->all(), [
                'name' => 'required|min:3',
            ],
            [
                'name.required' => 'Indique el nombre del menu',
                'name.min' => 'Mínimo tres caracteres para el nombre',
            ]
        );

        if ($validator->fails()) {
            return redirect('menu/'. $id .'/edit')
                        ->withErrors($validator)
                        ->with('error', 'Error en la validación del formulario')
                        ->withInput();
        }

        $menu = $this->menus($id)->first();
        $menu->name = $request->name;
        $menu->descripcion = $request->descripcion;
        $menu->save();

        return redirect('menu/'. $id .'/edit')->with('actualizado', 'El menú se ha actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function menus($id = ''){
        if($id == ''){
            $menus = Menus::orderBy('id', 'desc');
        }else
        {
            $menus = Menus::where('id', $id);
        }

        return $menus;
    }
}

resources/views/menu/create.blade.php
@extends('layout.index')

@section('libreriascss')
{{-- Formularios --}}
<!--Morris css-->
<link rel="stylesheet" href="{{url('assets/plugins/morris/morris.css')}}">
{{-- Notificaciones emergentes --}}
<!--Toastr css-->
<link rel="stylesheet" href="{{url('assets/plugins/toastr/build/toastr.css')}}">
<link rel="stylesheet" href="{{url('assets/plugins/toaster/garessi-notif.css')}}">
@endsection

@section('cuerpo')
{{-- Formularios - General Elements --}}
<div class="row">
	<div class="col-lg-12">
		<div class="card">
			<div class="card-header">
				<h4>Nuevo menú</h4>
			</div>
			<div class="card-body">
				<form name="frmMenus" class="form-horizontal" method="POST" action="{{route('menu.store')}}">
					@csrf
					<div class="form-group row">
						<label class="col-md-3 col-form-label">Nombre</label>
						<div class="col-md-9">
							<input type="text" name="name" id="name" class="form-control" value="{{old('name')}}">
						</div>
					</div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label">Descripción</label>
						<div class="col-md-9">
							<textarea class="form-control" name="descripcion" rows="6">{{old('descripcion')}}</textarea>
						</div>
					</div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label"></label>
						<div class="col-md-9">
							<button type="submit" class="btn btn-info">Guardar</button>
							<a href="{{route('menu.index')}}" class="btn btn-primary">Cancelar</a>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

@if(session('creado'))
	<div style="display: none;" id="creado" name="creado" class="alert alert-success" data-mensaje="{{session('creado')}}"></div>
@endif
@if($errors->has('name'))
	<div style="display: none;" id="error" name="error" class="alert alert-success" data-mensaje="{{$errors->first('name')}}"></div>
@endif

@endsection

@section('libreriasjavascript')
{{-- Notificaciones emergentes --}}
<!--Toastr js-->
<script src="{{url('assets/plugins/toastr/build/toastr.min.js')}}"></script>
<script src="{{url('assets/plugins/toaster/garessi-notif.js')}}"></script>
@endsection

@section('javascript')
<script type="text/javascript">
$(document).ready(function($) {
	if($('#creado').length){
		$mensaje = $('#creado').data('mensaje');
		toastr.success($mensaje, 'inBe');
	}
	if($('#error').length){
		$mensaje = $('#error').data('mensaje');
		toastr.error($mensaje, 'inBe');
	}
});
</script>
@endsection

resources/views/menu/edit.blade.php
@extends('layout.index')

@section('libreriascss')
{{-- Formularios --}}
<!--Morris css-->
<link rel="stylesheet" href="{{url('assets/plugins/morris/morris.css')}}">
{{-- Notificaciones emergentes --}}
<!--Toastr css-->
<link rel="stylesheet" href="{{url('assets/plugins/toastr/build/toastr.css')}}">
<link rel="stylesheet" href="{{url('assets/plugins/toaster/garessi-notif.css')}}">
@endsection

@section('cuerpo')
{{-- Formularios - General Elements --}}
<div class="row">
	<div class="col-lg-12">
		<div class="card">
			<div class="card-header">
				<h4>Nuevo menú</h4>
			</div>
			<div class="card-body">
				<form name="frmMenus" class="form-horizontal" method="POST" action="{{action('menu\menuController@update', ['id' => $menu->id])}}">
					@csrf
					@method('PUT')
					<div class="form-group row">
						<label class="col-md-3 col-form-label">Nombre</label>
						<div class="col-md-9">
							<input type="text" name="name" id="name" class="form-control" value="{{old('name') ? old('name') : $menu->name}}">
						</div>
					</div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label">Descripción</label>
						<div class="col-md-9">
							<textarea class="form-control" name="descripcion" rows="6">{{old('descripcion') ? old('descripcion') : $menu->descripcion}}</textarea>
						</div>
					</div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label"></label>
						<div class="col-md-9">
							<button type="submit" class="btn btn-info">Guardar</button>
							<a href="{{route('menu.index')}}" class="btn btn-primary">Cancelar</a>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

@if(session('actualizado'))
	<div style="display: none;" id="actualizado" name="actualizado" class="alert alert-success" data-mensaje="{{session('actualizado')}}"></div>
@endif
@if($errors->has('name'))
	<div style="display: none;" id="error" name="error" class="alert alert-success" data-mensaje="{{$errors->first('name')}}"></div>
@endif

@endsection

@section('libreriasjavascript')
{{-- Notificaciones emergentes --}}
<!--Toastr js-->
<script src="{{url('assets/plugins/toastr/build/toastr.min.js')}}"></script>
<script src="{{url('assets/plugins/toaster/garessi-notif.js')}}"></script>
@endsection

@section('javascript')
<script type="text/javascript">
$(document).ready(function($) {
	if($('#actualizado').length){
		$mensaje = $('#actualizado').data('mensaje');
		toastr.success($mensaje, 'inBe');
	}
	if($('#error').length){
		$mensaje = $('#error').data('mensaje');
		toastr.error($mensaje, 'inBe');
	}
});
</script>
@endsection

resources/views/menu/index.blade.php
@extends('layout.index')

@section('libreriascss')

@endsection

@section('cuerpo')
{{-- Hover Table - Headercolor Table --}}
<div class="row">
	<div class="col-lg-12">
		<div class="card">
			<div class="card-header">
				<h4>Menus</h4>
			</div>
			<div class="card-body">
				<div class="table-responsive">
					<table class="table table-bordered table-hover mb-0 text-nowrap">
						<tr>
							<th>#</th>
							<th>Nombre</th>
							<th>Descripción</th>
							<th></th>
						</tr>
						@foreach($menus as $menu)
						<tr>
							<td>{{$menu->id}}</td>
							<td>{{$menu->name}}</td>
							<td>{{Str::limit($menu->descripcion, 25)}}</td>
							<td>
								<a class="btn btn-info" href="{{action('menu\menuController@edit', ['id' => $menu->id])}}">Editar</a>
							</td>
						</tr>
						@endforeach
					</table>
					{{ $menus->links() }}
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

@section('libreriasjavascript')

@endsection

@section('javascript')
@endsection