routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
/*
|--------------------------------------------------------------------------
| Plantilla
|--------------------------------------------------------------------------
| Ruta para la plantilla y todos sus elementos
|
*/

Route::get('/plantilla', function () {
    return view('plantilla/index');
});

Auth::routes();

Auth::routes(['verify' => true]);

Route::get('/password', function(){
    return redirect()->route('password.update');
});
Route::get('/resetcomplete', function(){
    Auth::logout();
    return view('auth/resetcomplete');
});

/*
|--------------------------------------------------------------------------
| Rutas con autenticación
|--------------------------------------------------------------------------
| Rutas para usuarios logueados
|
*/

Route::get('signup/activate/{user}/code/{code}', 'SignupActivateController@activarCuentaApi');

Route::middleware(['auth'])->group(function(){
	/*
	| Dashboard
	*/
	// Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/', 'dashboard\dashboardController@index');
	Route::get('/home', 'dashboard\dashboardController@index')->name('home');

	/*
	| Roles
	*/
	Route::resource('/roles', 'roles\rolesController');
	Route::get('/roles/{role}/servicios', 'roles\serviciosController@index');
	Route::post('/roles/{role}/servicios', 'roles\serviciosController@store');

	/*
	| Menu
	*/
	Route::resource('/menu', 'menu\menuController');

	/*
	| Servicios
	*/
	Route::resource('/servicios', 'servicios\serviciosController');
	Route::post('/servicios/{id}', 'servicios\serviciosController@servicioDetalles');
	Route::get('/nuevos_servicios', 'servicios_al_cliente\servicios_al_clienteController@index')->name('servicios_al_cliente.index');
	Route::post('/nuevos_servicios/buscar', 'servicios_al_cliente\servicios_al_clienteController@buscar')->name('servicios_al_cliente.buscar');
	Route::post('/nuevos_servicios/mostrar', 'servicios_al_cliente\servicios_al_clienteController@mostrar')->name('servicios_al_cliente.mostrar');
	Route::post('/nuevos_servicios/cformula', 'servicios_al_cliente\servicios_al_clienteController@cformula')->name('servicios_al_cliente.cformula');
	Route::post('/nuevos_servicios/pformula', 'servicios_al_cliente\servicios_al_clienteController@pformula')->name('servicios_al_cliente.pformula');
	Route::post('/nuevos_servicios/hacer', 'servicios_al_cliente\servicios_al_clienteController@hacer')->name('servicios_al_cliente.hacer');
	Route::post('/nuevos_servicios/cuse', 'servicios_al_cliente\servicios_al_clienteController@cuse')->name('servicios_al_cliente.cuse');
	Route::post('/nuevos_servicios/puse', 'servicios_al_cliente\servicios_al_clienteController@puse')->name('servicios_al_cliente.puse');
	Route::post('/nuevos_servicios/recibir', 'servicios_al_cliente\servicios_al_clienteController@recibir')->name('servicios_al_cliente.recibir');

	// Route::get('/Hacer_nohacer', 'hacer_no_hacer\hacerNoHacerController@index')->name('hacer_no_hacer.index');
	// Route::post('/Hacer_nohacer', 'hacer_no_hacer\hacerNoHacerController@store')->name('hacer_no_hacer.store');
	// Route::get('/Hacer_nohacer/{id}', 'hacer_no_hacer\hacerNoHacerController@edit')->name('hacer_no_hacer.edit');
	// Route::post('/Hacer_nohacer/{id}', 'hacer_no_hacer\hacerNoHacerController@update')->name('hacer_no_hacer.update');
	// Route::get('/Hacer_nohacer/destroy/{id}', 'hacer_no_hacer\hacerNoHacerController@destroy')->name('hacer_no_hacer.destroy');

	Route::get('/do/{ye}', 'hacer_no_hacer\hacerNoHacerController@index')->name('hacer_no_hacer.index');
	Route::post('/do', 'hacer_no_hacer\hacerNoHacerController@store')->name('hacer_no_hacer.store');
	Route::get('/do /{id?}', 'hacer_no_hacer\hacerNoHacerController@edit')->name('hacer_no_hacer.edit');
	Route::post('/do /{id}', 'hacer_no_hacer\hacerNoHacerController@update')->name('hacer_no_hacer.update');
	Route::get('/do/destroy/{id}', 'hacer_no_hacer\hacerNoHacerController@destroy')->name('hacer_no_hacer.destroy');

	Route::get('/dont/{ye}', 'hacer_no_hacer\hacerNoHacerController@index')->name('nohacer_no_hacer.index');
	Route::post('/dont', 'hacer_no_hacer\hacerNoHacerController@store')->name('nohacer_no_hacer.store');
	Route::get('/dont/{id}', 'hacer_no_hacer\hacerNoHacerController@edit')->name('nohacer_no_hacer.edit');
	Route::post('/dont/{id}', 'hacer_no_hacer\hacerNoHacerController@update')->name('nohacer_no_hacer.update');
	Route::get('/dont/destroy/{id}', 'hacer_no_hacer\hacerNoHacerController@destroy')->name('nohacer_no_hacer.destroy');
	
	
	

	

	
	/*
	| Producto
	*/
	// Route::resource('/producto/marca', 'producto\marcaController');
	Route::resource('/marca', 'producto\marcaController');
	Route::get('/producto/marca/categoria/{id?}', 'producto\marcaController@marcaCategoria')->name('marca.categoria');
	// Route::resource('/producto/categoria', 'producto\categoriaController');
	Route::resource('/categoria', 'producto\categoriaController');
	Route::resource('/producto/producto', 'producto\productoController');
	Route::get('/importar/producto/', 'producto\importarController@index')->name('producto.importar');
	Route::post('/importar/producto/importar', 'producto\importarController@subirArchivo')->name('producto.subir.archivo');
	Route::get('/producto/exportar/formato', 'producto\exportarController@exportarFormatoModeloProducto')->name('producto.exportar.formato');
	Route::get('/producto/exportar/productos', 'producto\exportarController@exportarProductos')->name('producto.exportar.productos');

	/*
	| Mis categorias
	*/
	Route::get('/categorias/buscarProfesional', 'usuarios\CategoriasController@buscarProfesional')->name('categorias.buscarProfesional');
	Route::get('/categorias/usuario/{id?}', 'usuarios\CategoriasController@categoriasUsuario')->name('categorias.usuario');
	Route::post('/categorias/usuario/guardar', 'usuarios\CategoriasController@categoriasUsuarioGuardar')->name('categorias.usuario.guardar');
	Route::get('/categorias/listarCategorias', 'usuarios\CategoriasController@listarCategorias')->name('categorias.listarCategorias');
	Route::get('/miscategorias/usuario/{id}', 'usuarios\MisCategoriasController@index');
	Route::post('/miscategorias/usuario/{id}', 'usuarios\MisCategoriasController@modificarCategorias');
	Route::resource('/categorias', 'usuarios\CategoriasController');
	Route::post('/categorias/buscar', 'usuarios\CategoriasController@buscarCategorias')->name('categorias.buscar');

	/*
	| Administrar usuarios
	*/
	Route::resource('/usuarios', 'usuarios\UsuariosController');




});

app/Servicios.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Servicios extends Model
{
    protected $table = 'servicios';

    protected $fillable = [
        'name', 'descripcion',
    ];
}

app/Http/Controllers/roles/serviciosController.php
<?php

namespace App\Http\Controllers\roles;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Controllers\roles\rolesController;
use App\Http\Controllers\servicios\serviciosController as Serv;
use App\RolesServicios;


class serviciosController extends Controller
{
    public function index($id){

    	$rol = new rolesController;
    	$rol = $rol->roles($id)->first();

    	$servicios = new Serv;
    	$servicios = $servicios->servicios()->get();

    	$serviciosAsociados = [];
    	foreach($rol->servicios as $servicio){
			$serviciosAsociados[] = $servicio->servicios->id;
		}

    	
    	return view('roles.servicios', compact('rol', 'servicios', 'serviciosAsociados'));

    }

    public function store(Request $request, $id){

    	$datos = [
    		'rol' => $id,
    		'servicio' => $request->servicio,
    	];

    	if($request->metodo=='agregar'){
    		$operacion = $this->agregar($datos);
    	}

    	if($request->metodo=='quitar'){
    		$operacion = $this->quitar($datos);
    	}

    	// if($operacion)
    	// 	return response()->json([$request->servicio, $request->metodo, $id]);

    	return response()->json($operacion);
    }

    public function agregar($datos){

    	try {
    		$rolServicio = RolesServicios::where('roles_id', $datos['rol'])
    										->where('servicios_id', $datos['servicio'])
											->firstOrFail();
    	} catch (\Exception $e) {
    		$rolServicio = new RolesServicios;
    	}

    	try {
    		// $rolServicio = new RolesServicios;
	    	$rolServicio->roles_id = $datos['rol'];
	    	$rolServicio->servicios_id = $datos['servicio'];
	    	$rolServicio->activo = 1;
	    	$rolServicio->save();

	    	return true;
    		
    	} catch (\Exception $e) {
    		return false;
    	}
    }

    public function quitar($datos){

    	try {
    		$rolServicio = RolesServicios::where('roles_id', $datos['rol'])
										->where('servicios_id', $datos['servicio'])->first();
	    	// $rolServicio->roles_id = $datos['rol'];
	    	// $rolServicio->servicios_id = $datos['servicio'];
	    	$rolServicio->activo = 0;
	    	$rolServicio->save();

	    	return true;
    		
    	} catch (\Exception $e) {
    		return $e;
    	}

    }
}

app/Http/Controllers/servicios/serviciosController.php
<?php

namespace App\Http\Controllers\servicios;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;
use App\Servicios;
use App\Servicios_al_cliente;
use App\Servicios_al_cliente_formula;
use Auth;
use App\Servicios_al_cliente_formula_productos;

class serviciosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $servicios = $this->servicios()->paginate(10);
        $servicios =Servicios_al_cliente::all();
       
        return view('servicios.index', compact('servicios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('servicios.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make(
            $request->all(), [
                'name' => 'required|min:3',
            ],
            [
                'name.required' => 'Indique el nombre del servicio',
                'name.min' => 'Mínimo tres caracteres para el nombre',
            ]
        );

        if ($validator->fails()) {
            return redirect('servicios/create')
                        ->withErrors($validator)
                        ->with('error', 'Error en la validación del formulario')
                        ->withInput();
        }

        $servicio = new Servicios;
        $servicio->name = $request->name;
        $servicio->descripcion = $request->descripcion;
        $servicio->save();

        return redirect('servicios/create')->with('creado', 'Nuevo servicios creado');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $servicio = $this->servicios($id)->first();
        return view('servicios.edit', compact('servicio'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make(
            $request->all(), [
                'name' => 'required|min:3',
            ],
            [
                'name.required' => 'Indique el nombre del servicio',
                'name.min' => 'Mínimo tres caracteres para el nombre',
            ]
        );

        if ($validator->fails()) {
            return redirect('servicios/'. $id .'/edit')
                        ->withErrors($validator)
                        ->with('error', 'Error en la validación del formulario')
                        ->withInput();
        }

        $servicio = $this->servicios($id)->first();
        $servicio->name = $request->name;
        $servicio->descripcion = $request->descripcion;
        $servicio->save();

        return redirect('servicios/'. $id .'/edit')->with('actualizado', 'Servicio actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function servicios($id = ''){
        if($id == ''){
            $servicios = Servicios::orderBy('id', 'desc');
        }else
        {
            $servicios = Servicios::where('id', $id);
        }

        return $servicios;
    }

    public function servicioDetalles(Request $r){

        $servicios =Servicios_al_cliente::with(['formula.productos.producto', 'recomendaciones.dodont', 'recomendaciones.use.producto', 'cliente', 'profesional'])->findOrFail($r->id);

        // $servicios =Servicios_al_cliente_formula::all()->where('servicio_id','=',$r->id);
        // $formula='';
        // foreach($servicios as $s)
        // {
        //     $formula=$s->id;
        // }

        // $formula_producto =Servicios_al_cliente_formula_productos::all()->where('formula_id','=',$formula);
        

        // http_response_code(500);
        // dd($servicios );
  
        // $compra = Servicios_al_cliente::with(['cliente', 'detalles.presentacion.obra', 'detalles.producto'])->findOrFail($r->id);
        return response()->json($servicios);
        
    }

}

resources/views/servicios/create.blade.php
@extends('layout.index')

@section('libreriascss')
{{-- Formularios --}}
<!--Morris css-->
<link rel="stylesheet" href="{{url('assets/plugins/morris/morris.css')}}">
{{-- Notificaciones emergentes --}}
<!--Toastr css-->
<link rel="stylesheet" href="{{url('assets/plugins/toastr/build/toastr.css')}}">
<link rel="stylesheet" href="{{url('assets/plugins/toaster/garessi-notif.css')}}">
@endsection

@section('cuerpo')
{{-- Formularios - General Elements --}}
<div class="row">
	<div class="col-lg-12">
		<div class="card">
			<div class="card-header">
				<h4>Nuevo Servicios</h4>
			</div>
			<div class="card-body">
				<form name="frmServicios" class="form-horizontal" method="POST" action="{{route('servicios.store')}}">
					@csrf
					<div class="form-group row">
						<label class="col-md-3 col-form-label">Nombre</label>
						<div class="col-md-9">
							<input type="text" name="name" id="name" class="form-control" value="{{old('name')}}">
						</div>
					</div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label">Descripción</label>
						<div class="col-md-9">
							<textarea class="form-control" name="descripcion" rows="6">{{old('descripcion')}}</textarea>
						</div>
					</div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label"></label>
						<div class="col-md-9">
							<button type="submit" class="btn btn-info">Guardar</button>
							<a href="{{route('servicios.index')}}" class="btn btn-primary">Cancelar</a>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

@if(session('creado'))
	<div style="display: none;" id="creado" name="creado" class="alert alert-success" data-mensaje="{{session('creado')}}"></div>
@endif
@if($errors->has('name'))
	<div style="display: none;" id="error" name="error" class="alert alert-success" data-mensaje="{{$errors->first('name')}}"></div>
@endif

@endsection

@section('libreriasjavascript')
{{-- Notificaciones emergentes --}}
<!--Toastr js-->
<script src="{{url('assets/plugins/toastr/build/toastr.min.js')}}"></script>
<script src="{{url('assets/plugins/toaster/garessi-notif.js')}}"></script>
@endsection

@section('javascript')
<script type="text/javascript">
$(document).ready(function($) {
	if($('#creado').length){
		$mensaje = $('#creado').data('mensaje');
		toastr.success($mensaje, 'inBe');
	}
	if($('#error').length){
		$mensaje = $('#error').data('mensaje');
		toastr.error($mensaje, 'inBe');
	}
});
</script>
@endsection

resources/views/servicios/edit.blade.php
@extends('layout.index')

@section('libreriascss')
{{-- Formularios --}}
<!--Morris css-->
<link rel="stylesheet" href="{{url('assets/plugins/morris/morris.css')}}">
{{-- Notificaciones emergentes --}}
<!--Toastr css-->
<link rel="stylesheet" href="{{url('assets/plugins/toastr/build/toastr.css')}}">
<link rel="stylesheet" href="{{url('assets/plugins/toaster/garessi-notif.css')}}">
@endsection

@section('cuerpo')
{{-- Formularios - General Elements --}}
<div class="row">
	<div class="col-lg-12">
		<div class="card">
			<div class="card-header">
				<h4>Nuevo Rol</h4>
			</div>
			<div class="card-body">
				<form name="frmServicios" class="form-horizontal" method="POST" action="{{action('servicios\serviciosController@update', ['id' => $servicio->id])}}">
					@csrf
					@method('PUT')
					<div class="form-group row">
						<label class="col-md-3 col-form-label">Nombre</label>
						<div class="col-md-9">
							<input type="text" name="name" id="name" class="form-control" value="{{old('name') ? old('name') :  $servicio->name}}">
						</div>
					</div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label">Descripción</label>
						<div class="col-md-9">
							<textarea class="form-control" name="descripcion" rows="6">{{old('descripcion') ? old('descripcion') :$servicio->descripcion}}</textarea>
						</div>
					</div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label"></label>
						<div class="col-md-9">
							<button type="submit" class="btn btn-info">Guardar</button>
							<a href="{{route('servicios.index')}}" class="btn btn-primary">Cancelar</a>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

@if(session('actualizado'))
	<div style="display: none;" id="actualizado" name="actualizado" class="alert alert-success" data-mensaje="{{session('actualizado')}}"></div>
@endif
@if($errors->has('name'))
	<div style="display: none;" id="error" name="error" class="alert alert-success" data-mensaje="{{$errors->first('name')}}"></div>
@endif

@endsection

@section('libreriasjavascript')
{{-- Notificaciones emergentes --}}
<!--Toastr js-->
<script src="{{url('assets/plugins/toastr/build/toastr.min.js')}}"></script>
<script src="{{url('assets/plugins/toaster/garessi-notif.js')}}"></script>
@endsection

@section('javascript')
<script type="text/javascript">
$(document).ready(function($) {
	if($('#actualizado').length){
		$mensaje = $('#actualizado').data('mensaje');
		toastr.success($mensaje, 'inBe');
	}
	if($('#error').length){
		$mensaje = $('#error').data('mensaje');
		toastr.error($mensaje, 'inBe');
	}
});
</script>
@endsection

resources/views/servicios/index.blade.php
@extends('layout.index')

@section('libreriascss')

<style>

.modal-header{

	background: linear-gradient(#3d4192, #5d61bf) !important;
    color: white !important;
}

.table thead th {
    
    background: linear-gradient(#3d4192, #5d61bf) !important;
    color: white !important; 
}

.modal-dialog {
    max-width: 50%;
}


</style>

@endsection

@section('cuerpo')
{{-- Hover Table - Headercolor Table --}}
<div class="row">
@csrf
	<div class="col-lg-12">
		<div class="card">
			<div class="card-header">
				<h4>Roles</h4>
			</div>
			<div class="card-body">
				<div class="table-responsive">
					<table class="table table-bordered table-hover mb-0 text-nowrap">
						<tr>
							<th>#</th>
							<th>Nombre del profesional</th>
							<th>Nombre del servicio</th>
							<th>Nombre del cliente</th>
							<th>descripción proceso</th>
							<th></th>
						</tr>
						<?php $a = 0; ?>
						@foreach($servicios as $servicio)
						<tr>
						<?php $a++; ?>
							<td>{{$a}}</td>
							<td>{{$servicio->profesional->name}}</td>
							<td>{{$servicio->formulas->name}}</td>
							<td>{{$servicio->cliente->name}}</td>
							<td>{{$servicio->formulas->descripcion_proceso}}</td>
							<td>
                                <span >
                                    <a class="btn btn-warning btn-lg mostrar" href="" data-toggle="modal" data-target="#myModal" data-href="{{$servicio->id}}">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                </span>
                            </td>
						</tr>
						@endforeach
					</table>
					
				</div>
			</div>
		</div>
	</div>
</div>


<div class="modal fade " id="myModal" tabindex="-1" role="dialog">
  <div class="modal-dialog " role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Detalles de producto</h4>
      </div>
      <div class="modal-body">

	  
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<input type="hidden" value="{{ csrf_token()}}" name="_token">
@endsection

@section('libreriasjavascript')



@endsection

@section('javascript')

<script>
$('#myModal').appendTo("body");

$(document).ready(function($) {
    $("#myModal").on("show.bs.modal", function(e) {
        var link = $(e.relatedTarget);

        
		var id = link.attr("data-href")
			if(id != '')
			{
					var _token = $('input[name="_token"]').val();
					$.ajax({
					url:"/servicios/"+id,
					method:"POST",
					data:{id:id, _token:_token},
							success:function(data){
									console.log(data.recomendaciones.use)

								var compraformato = "";
								//titulo cliente
									compraformato = compraformato + "<table class='table table-bordered'>";
										compraformato = compraformato + "<thead class='thead-color'>";
										compraformato = compraformato + "<tr>";
											compraformato = compraformato + "<th>Nombre del profesional</th>";
											compraformato = compraformato + "<th>Nombre del cliente</th>";
											compraformato = compraformato + "<th>Nombre del servicio</th>";
										compraformato = compraformato + "</tr>";
										compraformato = compraformato + "</thead>";
										compraformato = compraformato + "<tbody>";
										compraformato = compraformato + "<tr>";
											compraformato = compraformato + "<td>"+ data.profesional.name +"</td>";
											compraformato = compraformato + "<td>"+ data.cliente.name +"</td>";
											compraformato = compraformato + "<td>"+ data.formulas.name +"</td>";
										compraformato = compraformato + "</tr>";
										compraformato = compraformato + "</tbody>";
									compraformato = compraformato + "</table>";
								//titulo cliente

										

								//titulo producto
									compraformato = compraformato + "<h4>Productos de la formula:</h4><table class='table table-bordered'>";
										compraformato = compraformato + "<thead class='thead-color'>";
										compraformato = compraformato + "<tr>";
											compraformato = compraformato + "<th>Nombre del producto</th>";
											compraformato = compraformato + "<th>Cantidad</th>";
											compraformato = compraformato + "<th>Medida</th>";
										compraformato = compraformato + "</tr>";
										compraformato = compraformato + "</thead>";
										compraformato = compraformato + "<tbody>";
										for(i=0; i < data.formulas.productos.length; i++){
												compraformato = compraformato + "<tr>";
												compraformato = compraformato + "<td>"+data.formulas.productos[i].producto.nombre+"</td>";
												compraformato = compraformato + "<td>"+ data.formulas.productos[i]['cantidad'] +"</td>";
												compraformato = compraformato + "<td>"+ data.formulas.productos[i]['medida'] +"</td>";
												compraformato = compraformato + "</tr>";
										}
										compraformato = compraformato + "</tbody>";
									compraformato = compraformato + "</table>";
								//titulo producto

										

								//titulo Recomendaciones
								
									compraformato = compraformato + "<h4>Recomendaciones de la formula:</h4><table class='table table-bordered'>";
										compraformato = compraformato + "<thead class='thead-color'>";
										compraformato = compraformato + "<tr>";
											compraformato = compraformato + "<th>Tipo</th>";
											compraformato = compraformato + "<th>Recomendaciones</th>";
										compraformato = compraformato + "</tr>";
										compraformato = compraformato + "</thead>";
										compraformato = compraformato + "<tbody>";

										for(i=0; i < data.recomendaciones.dodont.length; i++){
												compraformato = compraformato + "<tr>";
												compraformato = compraformato + "<td>"+data.recomendaciones.dodont[i].tipo+"</td>";
												compraformato = compraformato + "<td>"+ data.recomendaciones.dodont[i].tarea +"</td>";
												compraformato = compraformato + "</tr>";
									
										}
										compraformato = compraformato + "</tbody>";
									compraformato = compraformato + "</table>";

								//titulo Recomendaciones

										

								//titulo Recomendaciones producto

										compraformato = compraformato + "<h4>Recomendacion de productos:</h4><table class='table table-bordered'>";
										compraformato = compraformato + "<thead class='thead-color'>";
										compraformato = compraformato + "<tr>";
											compraformato = compraformato + "<th>Nombre del producto</th>";
											compraformato = compraformato + "<th>Cantidad</th>";
										compraformato = compraformato + "<th>uso</th>";
										compraformato = compraformato + "</tr>";
										compraformato = compraformato + "</thead>";
										compraformato = compraformato + "<tbody>";

										for(i=0; i < data.recomendaciones.use.length; i++){
												compraformato = compraformato + "<tr>";
												compraformato = compraformato + "<td>"+data.recomendaciones.use[i].producto.nombre+"</td>";
												compraformato = compraformato + "<td>"+data.recomendaciones.use[i].cantidad +"</td>";
												compraformato = compraformato + "<td>"+data.recomendaciones.use[i].medida +"</td>";
												compraformato = compraformato + "</tr>";
									
										}
										compraformato = compraformato + "</tbody>";
									compraformato = compraformato + "</table>";
								
								//titulo Recomendaciones producto


								$("#myModal").find(".modal-body").html(compraformato);

							}
					});
			}
        
		

    });
})

</script>




@endsection